FAIL	some/tmp/pkg
[----------] Running tests from PanickingTest
[ RUN      ] PanickingTest.PanickingTest
panicking_test.go:39:
panic: foobar

some_file.go:0 (0x00000)
	com/jacobsa/ogletest._func_001: "panic: %v\n\n%s", r, debug.Stack())
/Users/jacobsa/go/root/src/pkg/runtime/proc.c:1386 (0x10e69)
	panic: reflect·call(d->fn, d->args, d->siz);
some_file.go:0 (0x00000)
	com/jacobsa/ogletest/tmp-panicking_test-740123162_test.(*PanickingTest).PanickingTest: panic("foobar")
some_file.go:0 (0x00000)
	Value.call: call(fn, unsafe.Pointer(ptr), uint32(size))
some_file.go:0 (0x00000)
	Value.Call: return v.call("Call", in)
some_file.go:0 (0x00000)
	com/jacobsa/ogletest.runMethodIfExists: method.Call(argVals)
some_file.go:0 (0x00000)
	com/jacobsa/ogletest.runTest: runMethodIfExists(suiteInstance, method.Name)
some_file.go:0 (0x00000)
	com/jacobsa/ogletest.runTestsInternal: failures := runTest(suite, method)
some_file.go:0 (0x00000)
	com/jacobsa/ogletest._func_002: runTestsOnce.Do(func() { runTestsInternal(t) })
some_file.go:0 (0x00000)
	(*Once).Do: f()
some_file.go:0 (0x00000)
	com/jacobsa/ogletest.RunTests: runTestsOnce.Do(func() { runTestsInternal(t) })
some_file.go:0 (0x00000)
	com/jacobsa/ogletest/tmp-panicking_test-740123162_test.TestOgletest: func TestOgletest(t *testing.T) { RunTests(t) }
some_file.go:0 (0x00000)
	tRunner: test.F(t)
/Users/jacobsa/go/root/src/pkg/runtime/proc.c:258 (0xf00b)
	goexit: runtime·goexit(void)


[  FAILED  ] PanickingTest.PanickingTest
[ RUN      ] PanickingTest.ZzzSomeOtherTest
[       OK ] PanickingTest.ZzzSomeOtherTest
[----------] Finished with tests from PanickingTest
--- FAIL: sometest (0.00 seconds)
FAIL
